### ISSUE TITLE
Outdated Version support, YTMD V2 is about to release

### ISSUE THREAD

**Issue by Yellowbebo** [Gsimken/YTMD-deckboard#1]
Program is outdated, there is a new V2 Release coming out soon
if you dont update this, i just might

**Comment by Gsimken** [comment]
Thanks for the info, i will be working on it!

**Comment by BeboBabaYellow** [comment]
Alright, please let me know or just close this issue when you do, appreciate'ya

**Comment by NikitaSH999** [comment]
Hello, is any progress here?

**Comment by Yellowbebo** [comment]
No idea bud, im hoping there is myself

**Comment by Yellowbebo** [comment]
This post is closed until the owner of the YTMD Extension decides to reopen it to let us know he's done it
